global:
  enable_gh_proxy: false
  gh_proxy: "https://v6.gh-proxy.org/"
  split_cnip: true
  singbox:      {enable: true, single_file: false, json: true, srs: true}
  mihomo:       {enable: true, single_file: false, txt: false, yaml: true, mrs: true}
  v2ray:        {enable: true, single_file: false}
  surge:        {enable: true, single_file: true}
  loon:         {enable: true, single_file: true}
  stash:        {enable: true, single_file: true}
  egern:        {enable: true, single_file: true}
  shadowrocket: {enable: true, single_file: true}
  quantumultx:  {enable: true, single_file: true}

categories:
  - name: Speedtest
    upstreams:
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/speedtest.list"}

  - name: EasyPrivacy
    publish_adblock: true
    publish_dnsmasq: true
    publish_smartdns: true
    upstreams:
      - {url: "https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/mrs/BanEasyPrivacy_domain.list"}
      - {url: "https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Clash-Classical.yaml"}
      - {url: "https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/mrs/BanEasyPrivacy_ip.list"}

  - name: Meta
    upstreams:
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/meta.list"}
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/facebook.list"}
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Threads/Threads.list"}
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Facebook/Facebook.list"}
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Whatsapp/Whatsapp.list"}
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Instagram/Instagram.list"}

  - name: GitHub
    upstreams:
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.list"}
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GitHub/GitHub.list"}


  - name: Reddit
    upstreams:
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/reddit.list"}

  - name: Notion
    upstreams:
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/notion.list"}

  - name: AI
    upstreams:
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/openai.list"}
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/anthropic.list"}

  - name: Google
    upstreams:
      - {url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/google.txt"}
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list"}
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/googlefcm.list"}
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.list"}

  - name: Telegram
    upstreams:
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list"}
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.list"}
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip.list"}

  - name: X
    upstreams:
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.list"}
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geosite/twitter.list"}
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/twitter.list"}

  - name: YouTube
    upstreams:
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.list"}

  - name: Netflix
    upstreams:
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.list"}
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.list"}

  - name: TikTok
    upstreams:
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.list"}
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.listt"}

  - name: Emby
    upstreams:
      - {url: "https://raw.githubusercontent.com/wakaka0230/rules.conf/main/rules/Emby.list"}

  - name: JP_Media
    upstreams:
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/abema.list"}
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/dmm.list"}
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/unext.list"}

  - name: Discord
    upstreams:
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Discord/Discord.list"}
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/discord.list"}

  - name: Twitch
    upstreams:
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/twitch.list"}
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitch/Twitch.list"}

  - name: Microsoft
    upstreams:
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.list"}

  - name: Apple
    upstreams:
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.list"}
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list"}

  - name: Steam
    upstreams:
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam.list"}

  - name: Binance
    upstreams:
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam.list"}
  
  - name: OKX
    upstreams:
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/okx.list"}

  - name: Metamask
    upstreams:
      - {url: "https://raw.githubusercontent.com/wakaka0230/rules.conf/main/rules/Metamask.list"}

  - name: Trustwallet
    upstreams:
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/trustwallet.list"}    

  - name: Bybit
    upstreams:
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bybit.list"}

  - name: PayPal
    upstreams:
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.list"}

  - name: Redotpay
    upstreams:
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/redotpay.list"}

  - name: PT&BT
    upstreams:
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PrivateTracker/PrivateTracker.list"}

  - name: Lan
    upstreams:
      - {url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt"}
      - {url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt"}
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list"}

  - name: ChinaIPs
    upstreams:
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.list"}
